language: ruby
rvm:
- 2.0.0
sudo: false

branches:
  only:
  - master

script: bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site
