sudo: false
language: ruby
rvm: 2.0.0
cache: bundler
branches: { only: master }

script: bundle exec jekyll build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  on: { branch: master }
  skip_cleanup: true
  local_dir: _site
