# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kyle Alan Hale
author: Kyle Alan Hale
description: Some writing, some pictures, &c.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylealanhale.com" # the base hostname & protocol for your site, e.g. http://example.com

disqus:
  shortname: kah-writing
google_analytics: UA-25464550-3

# Build settings
markdown: kramdown
kramdown:
  footnote_backlink: '&#8617;&#65038;'
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - vendor

include: [_pages]
header_pages: [_pages/about.md]
permalink: :slug
excerpt_separator: <!--more-->
